-- Run this once in Supabase Dashboard -> SQL Editor.
-- Users live in Supabase's built-in auth.users (managed by Supabase Auth) —
-- role ('admin' | 'business_owner') and name are stored in each user's
-- user_metadata, set by the backend when the account is created.

create table if not exists businesses (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text,
  address text,
  city text default 'Tempe',
  state text default 'AZ',
  phone text,
  yelp_id text,
  google_place_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists chat_logs (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  role text not null check (role in ('user','assistant')),
  message text not null,
  created_at timestamptz default now()
);

create table if not exists signup_requests (
  id bigint generated by default as identity primary key,
  email text not null,
  name text,
  business_name text not null,
  google_match jsonb,
  status text default 'pending',
  created_at timestamptz default now()
);

-- Row Level Security: enabled with NO policies. That means the anon key
-- (used by the browser only for Supabase Auth login) has zero access to
-- these tables. All reads/writes go through the Express backend using the
-- service_role key, which bypasses RLS by design. Don't add public policies
-- unless you also start querying these tables directly from the browser.
alter table businesses enable row level security;
alter table chat_logs enable row level security;
alter table signup_requests enable row level security;
